### ISSUE TITLE
A better name for the organisation instead of CS-House.

### ISSUE THREAD

**Issue by g14a** [IIITDM-CS-CLUB/Feedback-Discussions#1]
All the members are invited to come up with new names for the organisation. Later we can have a poll or something to choose the best one.

**Comment by AkshaY2039** [comment]
Compusonic

**Comment by autolyticus** [comment]
**IIITDM-CS-Club** 

Short, simple and immediately obvious what it is.

**Comment by Akash-peaceout** [comment]
Bits and P.C's

**Comment by guptaanmol184** [comment]
**TCC** - The Coding Club

**Comment by g14a** [comment]
@guptaanmol184 sorry..TCC was already taken by some other organization..So finally IIITDM-CS-CLUB it is .. Closing the issue..
